// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GA.BDC.WebApi.Fundraising.Core.Templates.Emails
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Globalization;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class OrderCreatedEmailTemplate : OrderCreatedEmailTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n<html>\r\n<head>\r\n " +
                    "  <meta http-equiv=\"content-type\" content=\"text/html; charset=ISO-8859-1\">\r\n   <" +
                    "meta content=\"MSHTML 6.00.2800.1498\" name=\"GENERATOR\">\r\n   <title>");
            
            #line 12 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Subject));
            
            #line default
            #line hidden
            this.Write(@"</title>
   <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
</head>
<body bgcolor=""#FFFFFF"" style=""-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; height: 100% !important; width: 100% !important; background-color: #FFFFFF; margin: 0; padding: 0;"">
   <div itemscope itemtype=""http://schema.org/Order"">
      <div itemprop=""merchant"" itemscope itemtype=""http://schema.org/Organization"">
         <meta itemprop=""name"" content=""Fundraising.com"" />
      </div>
      <div itemprop=""customer"" itemscope itemtype=""http://schema.org/Person"">
         <meta itemprop=""name"" content=""");
            
            #line 21 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.FirstName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 21 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.LastName));
            
            #line default
            #line hidden
            this.Write("\" />\r\n      </div>\r\n      <meta itemprop=\"orderNumber\" content=\"");
            
            #line 23 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.Id));
            
            #line default
            #line hidden
            this.Write("\" />\r\n      <meta itemprop=\"priceCurrency\" content=\"USD\" />\r\n      <meta itemprop" +
                    "=\"price\" content=\"");
            
            #line 25 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales.Sum(p => p.TotalAmount).ToString(CultureInfo.InvariantCulture)));
            
            #line default
            #line hidden
            this.Write("\" />\r\n      <meta itemprop=\"orderStatus\" content=\"OrderInTransit\" />\r\n      <meta" +
                    " itemprop=\"paymentMethod\" content=\"");
            
            #line 27 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].PaymentMethod));
            
            #line default
            #line hidden
            this.Write("\" />\r\n      <meta itemprop=\"orderDate\" content=\"");
            
            #line 28 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.Today.ToShortDateString()));
            
            #line default
            #line hidden
            this.Write("\" />\r\n      ");
            
            #line 29 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
 foreach(var item in Sales.SelectMany(p => p.Items)) { 
            
            #line default
            #line hidden
            this.Write(@"         <div itemprop=""acceptedOffer"" itemscope itemtype=""http://schema.org/Offer"">
            <div itemprop=""itemOffered"" itemscope itemtype=""http://schema.org/Product"">
               <meta itemprop=""name"" content=""item.Product.Name"" />
            </div>
            <meta itemprop=""price"" content=""item.Product.CalculatedPrice"" />
            <meta itemprop=""priceCurrency"" content=""USD"" />
            <div itemprop=""eligibleQuantity"" itemscope itemtype=""http://schema.org/QuantitativeValue"">
               <meta itemprop=""value"" content=""item.Quantity"" />
            </div>
         </div>
      ");
            
            #line 40 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("   </div>\r\n   <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id" +
                    "=\"bodyTable\" style=\"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; " +
                    "background-color: #FFFFFF; border-collapse: collapse !important; height: 100% !i" +
                    "mportant; margin: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; padding: 0; w" +
                    "idth: 100% !important; border: 0;\" width=\"100%\">\r\n      <tbody>\r\n         <tr>\r\n" +
                    "            <td align=\"center\" id=\"bodyCell\" style=\"-webkit-text-size-adjust: 10" +
                    "0%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; he" +
                    "ight: 100% !important; width: 100% !important; border: 0; margin: 0; padding: 20" +
                    "px;\" valign=\"top\">\r\n               <!-- BEGIN TEMPLATE // -->\r\n               <t" +
                    "able border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"templateContainer\" style=\"-w" +
                    "ebkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt;" +
                    " mso-table-rspace: 0pt; border-collapse: collapse !important; width: 600px; bord" +
                    "er: 0;\">\r\n                  <tbody>\r\n                     <tr>\r\n                " +
                    "        <td align=\"center\" style=\"-webkit-text-size-adjust: 100%; -ms-text-size-" +
                    "adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" valign=\"top\">\r\n    " +
                    "                       <!-- BEGIN HEADER // -->\r\n                           <tab" +
                    "le border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"templateHeader\" style=\"-ms-tex" +
                    "t-size-adjust: 100%; -webkit-text-size-adjust: 100%; background-color: #e8e8e7; " +
                    "border-collapse: collapse !important; mso-table-lspace: 0pt; mso-table-rspace: 0" +
                    "pt\" width=\"100%\">\r\n                              <tbody>\r\n                      " +
                    "           <tr>\r\n                                    <td align=\"left\" class=\"hea" +
                    "derContent\" style=\"color: rgb(80, 80, 80); line-height: 20px; text-align: center" +
                    "; vertical-align: middle; padding: 0px;\" valign=\"top\" pardot-region=\"header_imag" +
                    "e\" pardot-data=\"\">\r\n                                       <img alt=\"Fundraising" +
                    ".com\" src=\"https://www.fundraising.com/Content/external/logoOrderConfirmationFun" +
                    "draising.png\" style=\"border-width: 0px; border-style: solid; width: 100%;\">\r\n   " +
                    "                                 </td>\r\n                                 </tr>\r\n" +
                    "                                 <tr>\r\n                                    <td>\r" +
                    "\n                                       <div style=\"font-size: xx-large; text-al" +
                    "ign: center; color: #808080; font-family: Helvetica;\">1.800.443.5353</div>\r\n    " +
                    "                                </td>\r\n                                 </tr>\r\n " +
                    "                             </tbody>\r\n                           </table>\r\n    " +
                    "                       <!-- // END HEADER -->\r\n                        </td>\r\n  " +
                    "                   </tr>\r\n                     <tr>\r\n                        <td" +
                    " align=\"center\" style=\"-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100" +
                    "%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" valign=\"top\">\r\n               " +
                    "            <!-- BEGIN BODY // -->\r\n                           <table border=\"0\"" +
                    " cellpadding=\"0\" cellspacing=\"0\" id=\"templateBody\" style=\"-ms-text-size-adjust: " +
                    "100%; -webkit-text-size-adjust: 100%; background-color: #FFFFFF; border-collapse" +
                    ": collapse !important; border-top-color: #FFFFFF; border-top-style: solid; borde" +
                    "r-top-width: 1px; mso-table-lspace: 0pt; mso-table-rspace: 0pt\" width=\"100%\">\r\n " +
                    "                             <tbody>\r\n                                 <tr>\r\n   " +
                    "                                 <td pardot-region=\"body_content\" align=\"left\" c" +
                    "lass=\"bodyContent\" style=\"color: rgb(128, 128, 128); font-size: 14px; line-heigh" +
                    "t: 21px; text-align: left; padding: 20px;\" valign=\"top\" pardot-data=\"\">\r\n       " +
                    "                                <p dir=\"ltr\" style=\"line-height: 1.15; margin-to" +
                    "p: 0pt; margin-bottom: 0pt;font-family: Helvetica;\">\r\n                          " +
                    "                <div style=\"text-align: right; font-size: large; font-family: He" +
                    "lvetica;\">\r\n                                             Order Confirmation Numb" +
                    "er: ");
            
            #line 78 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Id));
            
            #line default
            #line hidden
            this.Write("<br />Customer Number: ");
            
            #line 78 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.LeadId));
            
            #line default
            #line hidden
            this.Write("<br /><br />\r\n                                          </div>\r\n                 " +
                    "                         <div style=\"font-family: Helvetica;\">\r\n                " +
                    "                             <strong>Thank you for shopping with us ");
            
            #line 81 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.FirstName));
            
            #line default
            #line hidden
            this.Write(@"!</strong><br />
                                             Please verify all orders upon delivery - all damaged products should be refused at that time. No returns or refunds
                                             will be accepted after the order is signed for.<br /><br />
                                          </div>
                                          <div style=""background-color: #e8e8e7; color: black; font-weight: bold;"">
                                             <table style=""border: 0; width: 100%; font-size: larger;"">
                                                <tr>
                                                   <td style=""width: 50%; background-color: #e8e8e7;font-family: Helvetica;"">Billing Address</td>
                                                   <td style=""width: 50%; background-color: #e8e8e7; font-family: Helvetica;"">Shipping Address</td>
                                                </tr>
                                             </table>
                                          </div>
                                          <table style=""border: 0; width: 100%; font-size: 14px;"">
                                             <tr>
                                                <td style=""width: 50%; color: rgb(128, 128, 128);font-family: Helvetica;"">");
            
            #line 95 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.FirstName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 95 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.LastName));
            
            #line default
            #line hidden
            this.Write("<br />");
            
            #line 95 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.Addresses[0].Address1));
            
            #line default
            #line hidden
            this.Write("<br />");
            
            #line 95 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.Addresses[0].City));
            
            #line default
            #line hidden
            this.Write(" (");
            
            #line 95 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.Addresses[0].Region.Code));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 95 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.Addresses[0].PostCode));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                                                <td style=\"width: 50%; col" +
                    "or: rgb(128, 128, 128);font-family: Helvetica;\">");
            
            #line 96 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.Addresses[1].AttentionOf));
            
            #line default
            #line hidden
            this.Write("<br />");
            
            #line 96 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.Addresses[1].Address1));
            
            #line default
            #line hidden
            this.Write("<br />");
            
            #line 96 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.Addresses[1].City));
            
            #line default
            #line hidden
            this.Write(" (");
            
            #line 96 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.Addresses[1].Region.Code));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 96 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.Addresses[1].PostCode));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                                             </tr>\r\n                      " +
                    "                    </table>\r\n                                          <br />\r\n" +
                    "                                          <div style=\"background-color: #e8e8e7;" +
                    " color: black; font-weight: bold; font-size: larger;\">\r\n                        " +
                    "                     <table style=\"border: 0; width: 100%; font-size: larger;\">\r" +
                    "\n                                                <tr>\r\n                         " +
                    "                          <td style=\"width: 100%; background-color: #e8e8e7;font" +
                    "-family: Helvetica;\">Order</td>\r\n                                               " +
                    " </tr>\r\n                                             </table>\r\n                 " +
                    "                         </div>\r\n                                          <tabl" +
                    "e style=\"width: 100%; font-size: 14px;\">\r\n                                      " +
                    "       <thead>\r\n                                             <tr style=\"text-tra" +
                    "nsform: uppercase; font-weight: bold; color: rgb(128, 128, 128);\">\r\n            " +
                    "                                    <th style=\"text-align: left;font-family: Hel" +
                    "vetica;\">Product</th>\r\n                                                <th style" +
                    "=\"text-align: left;font-family: Helvetica;\">Quantity</th>\r\n                     " +
                    "                           <th style=\"text-align: left;font-family: Helvetica;\">" +
                    "Price</th>\r\n                                                <th style=\"text-alig" +
                    "n: left;font-family: Helvetica;\">Total</th>\r\n                                   " +
                    "          </tr>\r\n                                             </thead>\r\n        " +
                    "                                     <tbody>\r\n                                  " +
                    "              ");
            
            #line 117 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
 foreach(var item in Sales.SelectMany(p => p.Items)) { 
            
            #line default
            #line hidden
            this.Write("                                                <tr>\r\n                           " +
                    "                        <td style=\"color: rgb(128, 128, 128);font-family: Helvet" +
                    "ica;\">");
            
            #line 119 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Product.Name));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                                                   <td style=\"color: rgb(1" +
                    "28, 128, 128);font-family: Helvetica;\">");
            
            #line 120 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Quantity));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                                                   <td style=\"color: rgb(1" +
                    "28, 128, 128);font-family: Helvetica;\">");
            
            #line 121 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Product.CalculatedPrice.ToString("C")));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                                                   <td style=\"color: rgb(1" +
                    "28, 128, 128);font-family: Helvetica;\">");
            
            #line 122 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((item.Quantity * item.Product.CalculatedPrice).ToString("C")));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                                                </tr>\r\n                   " +
                    "                             ");
            
            #line 124 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"                                             </tbody>
                                             <tfoot>
                                                <tr>
                                                   <td colspan=""3"" style=""color: rgb(128, 128, 128);font-family: Helvetica;"">Subtotal:</td>
                                                   <td style=""font-family: Helvetica;color: rgb(128, 128, 128);"">");
            
            #line 129 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales.SelectMany(p => p.Items).Sum(p => p.Quantity * p.Product.CalculatedPrice).ToString("C")));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                                                </tr>\r\n                   " +
                    "                             ");
            
            #line 131 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
 if(Sales.Sum(p => p.TotalAmount) - Sales.SelectMany(p => p.Items).Sum(p => p.Quantity * p.Product.CalculatedPrice) - Sales.Where(p => p.PromotionCode != null).Sum(p => p.PromotionCode.DiscountedAmount) - Sales.Sum(p => p.Discounts) - Sales.Sum(p => p.Surcharges) > 0) { 
            
            #line default
            #line hidden
            this.Write(@"                                                   <tr>
                                                      <td colspan=""3"" style=""color: rgb(128, 128, 128);font-family: Helvetica;"">Shipping Fee:</td>
                                                      <td style=""font-family: Helvetica;color: rgb(128, 128, 128);"">");
            
            #line 134 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((Sales.Sum(p => p.TotalAmount) - Sales.SelectMany(p => p.Items).Sum(p => p.Quantity * p.Product.CalculatedPrice) - Sales.Where(p => p.PromotionCode != null).Sum(p => p.PromotionCode.DiscountedAmount) - Sales.Sum(p => p.Discounts) - Sales.Sum(p => p.Surcharges)).ToString("C")));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                                                   </tr>\r\n                " +
                    "                                ");
            
            #line 136 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                                                ");
            
            #line 137 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
 if(Sales.Any(p => p.PromotionCodeId > 0)) { 
            
            #line default
            #line hidden
            this.Write(@"                                                   <tr>
                                                      <td colspan=""3"" style=""color: rgb(128, 128, 128);font-family: Helvetica;"">Promotion Code:</td>
                                                      <td style=""font-family: Helvetica;color: rgb(128, 128, 128);"">- ");
            
            #line 140 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales.Where(p => p.PromotionCode != null).Sum(p => p.PromotionCode.DiscountedAmount).ToString("C")));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                                                   </tr>\r\n                " +
                    "                                ");
            
            #line 142 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                                                ");
            
            #line 143 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
 if(Sales.Sum(p => p.Discounts) > 0) { 
            
            #line default
            #line hidden
            this.Write(@"                                                   <tr>
                                                      <td colspan=""3"" style=""color: rgb(128, 128, 128);font-family: Helvetica;"">Discounts:</td>
                                                      <td style=""font-family: Helvetica;color: rgb(128, 128, 128);"">- ");
            
            #line 146 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales.Sum(p => p.Discounts).ToString("C")));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                                                   </tr>\r\n                " +
                    "                                ");
            
            #line 148 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                                                ");
            
            #line 149 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
 if(Sales.Sum(p => p.Surcharges) > 0) { 
            
            #line default
            #line hidden
            this.Write(@"                                                   <tr>
                                                      <td colspan=""3"" style=""color: rgb(128, 128, 128);font-family: Helvetica;"">Surcharges:</td>
                                                      <td style=""font-family: Helvetica;color: rgb(128, 128, 128);"">");
            
            #line 152 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales.Sum(p => p.Surcharges).ToString("C")));
            
            #line default
            #line hidden
            this.Write("</td>\r\n                                                   </tr>\r\n                " +
                    "                                ");
            
            #line 154 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"                                                <tr style=""font-weight: bold;"">
                                                   <td colspan=""3"" style=""color: rgb(128, 128, 128);font-family: Helvetica;"">Total:</td>
                                                   <td style=""font-family: Helvetica;color: rgb(128, 128, 128);"">");
            
            #line 157 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales.Sum(p => p.TotalAmount).ToString("C")));
            
            #line default
            #line hidden
            this.Write(@"</td>
                                                </tr>
                                             </tfoot>
                                          </table>
                                          <br />
                                          <div style=""background-color: #e8e8e7; color: black; font-weight: bold; font-size: larger;"">
                                             <table style=""border: 0; width: 100%; font-size: larger;"">
                                                <tr>
                                                   <td style=""width: 100%;background-color: #e8e8e7;font-family: Helvetica;"">Payment</td>
                                                </tr>
                                             </table>
                                          </div>
                                          <div style=""font-family: Helvetica;"">
                                             ");
            
            #line 170 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].PaymentMethod));
            
            #line default
            #line hidden
            this.Write(@"
                                          </div>
                                          <br />
                                          <div style=""background-color: #e8e8e7; color: black; font-weight: bold; font-size: larger;"">
                                             <table style=""border: 0; width: 100%; font-size: larger;"">
                                                <tr>
                                                   <td style=""width: 100%; background-color: #e8e8e7;font-family: Helvetica;"">Estimated Delivery Time</td>
                                                </tr>
                                             </table>
                                          </div>
                                          <div style=""font-family: Helvetica;"">
                                             ");
            
            #line 181 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.Today.AddDays(10).ToShortDateString()));
            
            #line default
            #line hidden
            this.Write(@" (Please allow 7-15 business days for delivery.)
                                          </div>
                                          <br />
                                          <div style=""background-color: white; color: black; font-weight: bold; font-size: larger;"">
                                             <table style=""border: 0; width: 100%; font-size: larger;"">
                                                <tr>
                                                   <td style=""width: 100%; text-align: center""><a style=""color: black;font-family: Helvetica;"" href=""https://www.fundraising.com/shopping-cart/order-confirmation/");
            
            #line 187 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.Id));
            
            #line default
            #line hidden
            this.Write(@""">View Order Online</a></td>
                                                </tr>
                                             </table>
                                          </div>
                                          <link itemprop=""url"" href=""https://www.fundraising.com/shopping-cart/order-confirmation/");
            
            #line 191 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.Id));
            
            #line default
            #line hidden
            this.Write(@""" />
                                          <div itemprop=""potentialAction"" itemscope itemtype=""http://schema.org/ViewAction"">
                                             <link itemprop=""target"" href=""https://www.fundraising.com/shopping-cart/order-confirmation/");
            
            #line 193 "C:\SourceCode\Southwestern-Fundraising\1.DEV\GA\BDC\WebApi\Core\Templates\Emails\OrderCreatedEmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sales[0].Client.Id));
            
            #line default
            #line hidden
            this.Write(@""" />
                                          </div>
                                          <br />
                                          <span style=""font-family: Helvetica;"">Best Regards,</span><br />
                                          <a style=""color: black;font-family: Helvetica;"" href=""https://www.fundraising.com?utm_source=fundraisingcom&utm_medium=email&utm_campaign=OrderConfirmation"">Fundraising.com Team</a><br />
                                          <a style=""color: black;font-family: Helvetica;"" href=""tel:+18004435353"">1.800.443.5353</a>
                                       </p>
                                    </td>
                                 </tr>
                              </tbody>
                           </table>
                           <!-- // END BODY -->
                        </td>
                     </tr>
                  </tbody>
               </table>
               <!-- // END TEMPLATE -->
            </td>
         </tr>
      </tbody>
   </table>

</body>
</html>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class OrderCreatedEmailTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
