////////////////////////////////////////////////////////////////////////////////////////////
// Class generated by SqlCodeGen 1.1.0.0.
// Do not edit this file directly. Changes will be lost when this file is regenerated.
// Extensions should be added in a separate file using partial classes.
////////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Data;
using System.Text;
using NHibernate;
using NHibernate.Expression;
using NHibernate.Mapping.Attributes;

namespace QSP.Business.Fulfillment
{
    [Serializable]
    [Class(Schema = "`dbo`", Table = "`commission_type`")]
    public partial class CommissionType
    {
        #region Constants
        public const string CommissionTypeEntity = "CommissionType";
        public const string CommissionTypeIdProperty = "CommissionTypeId";
        public const string CommissionTypeNameProperty = "CommissionTypeName";
        #endregion

        #region Fields
        protected int commissionTypeId = 0;
        protected string commissionTypeName = "";
        #endregion

        #region Constructors
        public CommissionType()
        {
        }
        #endregion

        #region Properties
        [RawXml(Content = @"
		<id name=""CommissionTypeId"" column=""`commission_type_id`"">
			<generator class=""native"">
			</generator>
		</id>")]

        public virtual int CommissionTypeId
        {
            get { return this.commissionTypeId; }
            set { this.commissionTypeId = value; }
        }

        [Property(Column = "`commission_type_name`")]
        public virtual string CommissionTypeName
        {
            get { return this.commissionTypeName; }
            set { this.commissionTypeName = value; }
        }
        #endregion

        #region Methods

        public static ICriteria CreateCriteria()
        {
            using (ISession session = SqlSessionManager.OpenSession())
            {
                ICriteria c = session.CreateCriteria(typeof(CommissionType));
                return c;
            }
        }


        public static CommissionType GetCommissionType(int commissionTypeId)
        {
            using (ISession session = SqlSessionManager.OpenSession())
            {
                return session.Get<CommissionType>(commissionTypeId);
            }
        }

        public static List<CommissionType> GetCommissionTypeList()
        {
            using (ISession session = SqlSessionManager.OpenSession())
            {
                ICriteria c = session.CreateCriteria(typeof(CommissionType));
                return (List<CommissionType>)c.List<CommissionType>();
            }
        }

        public static List<CommissionType> GetCommissionTypeList(string sortExpression, int maximumRows, int startRowIndex)
        {
            using (ISession session = SqlSessionManager.OpenSession())
            {
                ICriteria c = session.CreateCriteria(typeof(CommissionType));
                if (sortExpression != null && sortExpression != "")
                {
                    // Get ascending or descending order
                    bool descending = sortExpression.Contains(" DESC");

                    // Strip off ASC or DESC ordering
                    sortExpression = sortExpression.Replace(" ASC", "");
                    sortExpression = sortExpression.Replace(" DESC", "");
                    sortExpression = sortExpression.Trim();

                    // Get multi column sort from the comma delimited string
                    List<String> expressions = new List<String>();
                    if (sortExpression.Contains(","))
                    {
                        string[] tokens = sortExpression.Split(",".ToCharArray());
                        for (int i = 0; i < tokens.Length; i++)
                        {
                            tokens[i] = tokens[i].Trim();
                            if (tokens[i] != "")
                                expressions.Add(tokens[i]);
                        }
                    }
                    else if (sortExpression != "")
                    {
                        expressions.Add(sortExpression);
                    }

                    // Create the order
                    for (int i = 0; i < expressions.Count; i++)
                    {
                        if (descending)
                            c.AddOrder(NHibernate.Expression.Order.Desc(expressions[i]));
                        else
                            c.AddOrder(NHibernate.Expression.Order.Asc(expressions[i]));
                    }
                }

                // Set offset and limit
                if (startRowIndex >= 0)
                    c.SetFirstResult(startRowIndex);

                if (maximumRows >= 0)
                    c.SetMaxResults(maximumRows);

                return (List<CommissionType>)c.List<CommissionType>();
            }
        }

        public static List<CommissionType> GetCommissionTypeList(string sortExpression)
        {
            return GetCommissionTypeList(sortExpression, -1, -1);
        }

        public static List<CommissionType> GetCommissionTypeList(ICriteria criteria)
        {
            return (List<CommissionType>)criteria.List<CommissionType>();
        }

        public static void InsertCommissionType(CommissionType obj)
        {
            if (obj != null)
                obj.Insert();
        }

        public static void UpdateCommissionType(CommissionType obj)
        {
            if (obj != null)
                obj.Update();
        }

        public static void DeleteCommissionType(CommissionType obj)
        {
            if (obj != null)
                obj.Delete();
        }

        protected static CommissionType PopulateCommissionType(IDataReader r)
        {
            CommissionType obj = new CommissionType();
            obj.CommissionTypeId = (int)r["commission_type_id"];
            obj.CommissionTypeName = (string)r["commission_type_name"];

            return obj;
        }

        public static int GetCount()
        {
            using (ISession session = SqlSessionManager.OpenSession())
            {
                ICriteria c = session.CreateCriteria(typeof(CommissionType));
                c.SetProjection(Projections.RowCount());
                return (int)c.UniqueResult();
            }
        }

        /// <summary>
        /// Insert the entity to database.
        /// </summary>
        public virtual void Insert()
        {
            using (ISession session = SqlSessionManager.OpenSession())
            {
                ITransaction trans = session.BeginTransaction();
                try
                {
                    session.Save(this);
                    trans.Commit();
                }
                catch
                {
                    trans.Rollback();
                    throw;
                }
            }
        }

        /// <summary>
        /// Update the entity to database.
        /// </summary>
        public virtual void Update()
        {
            using (ISession session = SqlSessionManager.OpenSession())
            {
                ITransaction trans = session.BeginTransaction();
                try
                {
                    session.Update(this);
                    trans.Commit();
                }
                catch
                {
                    trans.Rollback();
                    throw;
                }
            }
        }

        /// <summary>
        /// Persist the entity back to database.
        /// </summary>
        public virtual void Save()
        {
            using (ISession session = SqlSessionManager.OpenSession())
            {
                ITransaction trans = session.BeginTransaction();
                try
                {
                    session.SaveOrUpdate(this);
                    trans.Commit();
                }
                catch
                {
                    trans.Rollback();
                    throw;
                }
            }
        }

        /// <summary>
        /// Delete entity in database.
        /// </summary>
        public virtual void Delete()
        {
            using (ISession session = SqlSessionManager.OpenSession())
            {
                ITransaction trans = session.BeginTransaction();
                try
                {
                    session.Delete(this);
                    trans.Commit();
                }
                catch
                {
                    trans.Rollback();
                    throw;
                }
            }
        }

        /// <summary>
        /// Local implementation of Equals based on unique value members
        /// </summary>
        public override bool Equals(object obj)
        {
            if (this == obj)
                return true;

            if ((obj == null) || (obj.GetType() != this.GetType()))
                return false;

            CommissionType castObj = (CommissionType)obj;
            return (castObj != null && this.commissionTypeId == castObj.CommissionTypeId);
        }

        /// <summary>
        /// Local implementation of GetHashCode based on unique value members
        /// </summary>
        public override int GetHashCode()
        {
            return 29 * (1 + this.commissionTypeId.GetHashCode());
        }





        #endregion
    }
}
