////////////////////////////////////////////////////////////////////////////////////////////
// Class generated by SqlCodeGen 1.1.0.0.
// Do not edit this file directly. Changes will be lost when this file is regenerated.
// Extensions should be added in a separate file using partial classes.
////////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Data;
using System.Text;
using NHibernate;
using NHibernate.Expression;
using NHibernate.Mapping.Attributes;

namespace QSP.Business.Fulfillment
{
	[Serializable]
	[Class(Schema="`dbo`", Table="`contact_type`")]
	public partial class ContactType
	{
		#region Constants
        public const string ContactTypeEntity = "ContactType";
		public const string ContactTypeIdProperty = "ContactTypeId";
		public const string ContactTypeNameProperty = "ContactTypeName";
		#endregion

		#region Fields
		protected int contactTypeId = 0;
		protected string contactTypeName = "";
		#endregion

		#region Constructors
		public ContactType() 
		{
		}
		#endregion

		#region Properties
		[RawXml(Content=@"
		<id name=""ContactTypeId"" column=""`contact_type_id`"">
			<generator class=""assigned"">
			</generator>
		</id>")]

		public virtual int ContactTypeId
		{
			get { return this.contactTypeId; }
			set { this.contactTypeId = value; }
		}

		[Property(Column="`contact_type_name`")]
		public virtual string ContactTypeName
		{
			get { return this.contactTypeName; }
			set { this.contactTypeName = value; }
		}
		#endregion

		#region Methods

        public static ICriteria CreateCriteria()
        {
            using (ISession session = SqlSessionManager.OpenSession())
            {
                ICriteria c = session.CreateCriteria(typeof(ContactType));
                return c;
            }
        }

        public static List<ContactType> GetContactTypeList(ICriteria criteria)
        {
            return (List<ContactType>)criteria.List<ContactType>();
        }

		public static ContactType GetContactType(int contactTypeId)
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				return session.Get<ContactType>(contactTypeId);
			}
		}

		public static List<ContactType> GetContactTypeList()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ICriteria c = session.CreateCriteria(typeof(ContactType));
				return (List<ContactType>)c.List<ContactType>();
			}
		}

		public static List<ContactType> GetContactTypeList(string sortExpression, int maximumRows, int startRowIndex)
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ICriteria c = session.CreateCriteria(typeof(ContactType));
				if (sortExpression != null && sortExpression != "")
				{
					// Get ascending or descending order
					bool descending = sortExpression.Contains(" DESC");

					// Strip off ASC or DESC ordering
					sortExpression = sortExpression.Replace(" ASC", "");
					sortExpression = sortExpression.Replace(" DESC", "");
					sortExpression = sortExpression.Trim();

					// Get multi column sort from the comma delimited string
					List<String> expressions = new List<String>();
					if (sortExpression.Contains(","))
					{
						string[] tokens = sortExpression.Split(",".ToCharArray());
						for (int i = 0; i < tokens.Length; i++)
						{
							tokens[i] = tokens[i].Trim();
							if (tokens[i] != "")
								expressions.Add(tokens[i]);
						}
					}
					else if (sortExpression != "")
					{
						expressions.Add(sortExpression);
					}

					// Create the order
					for (int i = 0; i < expressions.Count; i++)
					{
						if (descending)
							c.AddOrder(NHibernate.Expression.Order.Desc(expressions[i]));
						else
							c.AddOrder(NHibernate.Expression.Order.Asc(expressions[i]));
					}
				}

				// Set offset and limit
				if (startRowIndex >= 0)
					c.SetFirstResult(startRowIndex);

				if (maximumRows >= 0)
					c.SetMaxResults(maximumRows);

				return (List<ContactType>)c.List<ContactType>();
			}
		}

		public static List<ContactType> GetContactTypeList(string sortExpression)
		{
			return GetContactTypeList(sortExpression, -1, -1);
		}

		public static void InsertContactType(ContactType obj)
		{
			if (obj != null)
				obj.Insert();
		}

		public static void UpdateContactType(ContactType obj)
		{
			if (obj != null)
				obj.Update();
		}

		public static void DeleteContactType(ContactType obj)
		{
			if (obj != null)
				obj.Delete();
		}

        protected static ContactType PopulateContactType(IDataReader r)
		{
			ContactType obj = new ContactType();
			obj.ContactTypeId = (int)r["contact_type_id"];
			obj.ContactTypeName = (string)r["contact_type_name"];

			return obj;
		}

		public static int GetCount()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ICriteria c = session.CreateCriteria(typeof(ContactType));
				c.SetProjection(Projections.RowCount());
				return (int) c.UniqueResult();
			}
		}

		/// <summary>
		/// Insert the entity to database.
		/// </summary>
		public virtual void Insert()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ITransaction trans = session.BeginTransaction();
				try
				{
					session.Save(this);
					trans.Commit();
				}
				catch
				{
					trans.Rollback();
					throw;
				}
			}
		}

		/// <summary>
		/// Update the entity to database.
		/// </summary>
		public virtual void Update()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ITransaction trans = session.BeginTransaction();
				try
				{
					session.Update(this);
					trans.Commit();
				}
				catch
				{
					trans.Rollback();
					throw;
				}
			}
		}

		/// <summary>
		/// Delete entity in database.
		/// </summary>
		public virtual void Delete()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ITransaction trans = session.BeginTransaction();
				try
				{
					session.Delete(this);
					trans.Commit();
				}
				catch
				{
					trans.Rollback();
					throw;
				}
			}
		}

		/// <summary>
		/// Local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals(object obj)
		{
			if (this == obj)
				return true;

			if ((obj == null) || (obj.GetType() != this.GetType())) 
				return false;

			ContactType castObj = (ContactType)obj;
			return (castObj != null && this.contactTypeId == castObj.ContactTypeId);
		}

		/// <summary>
		/// Local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			return 29 * (1 + this.contactTypeId.GetHashCode());
		}
		#endregion
	}
}
