////////////////////////////////////////////////////////////////////////////////////////////
// Class generated by SqlCodeGen 1.1.0.0.
// Do not edit this file directly. Changes will be lost when this file is regenerated.
// Extensions should be added in a separate file using partial classes.
////////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Data;
using System.Text;
using NHibernate;
using NHibernate.Expression;
using NHibernate.Mapping.Attributes;

namespace QSP.Business.Fulfillment
{
	[Serializable]
	[Class(Schema="`dbo`", Table="`Discount_Rule_Type`")]
	public partial class DiscountRuleType
	{
		#region Constants
        public const string DiscountRuleTypeEntity = "DiscountRuleType";
		public const string DiscountRuleTypeIdProperty = "DiscountRuleTypeId";
		public const string NameProperty = "Name";
		public const string DescriptionProperty = "Description";
		public const string MultiUseTFProperty = "MultiUseTF";
		public const string MultiCustomerTFProperty = "MultiCustomerTF";
		public const string MultiOrderTFProperty = "MultiOrderTF";
		public const string CarryBalanceProperty = "CarryBalance";
		public const string CreateDateProperty = "CreateDate";
		public const string CreateUserIdProperty = "CreateUserId";
		public const string UpdateDateProperty = "UpdateDate";
		public const string UpdateUserIdProperty = "UpdateUserId";
		public const string DeletedProperty = "Deleted";
		#endregion

		#region Fields
		protected int discountRuleTypeId = 0;
		protected string name = "";
		protected string description = null;
		protected bool multiUseTF = false;
		protected bool multiCustomerTF = false;
		protected bool multiOrderTF = false;
		protected bool carryBalance = false;
		protected DateTime createDate = DateTime.Now;
		protected int createUserId = 0;
		protected DateTime? updateDate = DateTime.Now;
		protected string updateUserId = null;
		protected bool deleted = false;
		#endregion

		#region Constructors
		public DiscountRuleType() 
		{
		}
		#endregion

		#region Properties
		[RawXml(Content=@"
		<id name=""DiscountRuleTypeId"" column=""`Discount_Rule_Type_Id`"">
			<generator class=""native"">
			</generator>
		</id>")]

		public virtual int DiscountRuleTypeId
		{
			get { return this.discountRuleTypeId; }
			set { this.discountRuleTypeId = value; }
		}

		[Property(Column="`Name`")]
		public virtual string Name
		{
			get { return this.name; }
			set { this.name = value; }
		}

		[Property(Column="`Description`")]
		public virtual string Description
		{
			get { return this.description; }
			set { this.description = value; }
		}

		[Property(Column="`Multi_Use_TF`")]
		public virtual bool MultiUseTF
		{
			get { return this.multiUseTF; }
			set { this.multiUseTF = value; }
		}

		[Property(Column="`Multi_Customer_TF`")]
		public virtual bool MultiCustomerTF
		{
			get { return this.multiCustomerTF; }
			set { this.multiCustomerTF = value; }
		}

		[Property(Column="`Multi_Order_TF`")]
		public virtual bool MultiOrderTF
		{
			get { return this.multiOrderTF; }
			set { this.multiOrderTF = value; }
		}

		[Property(Column="`Carry_Balance`")]
		public virtual bool CarryBalance
		{
			get { return this.carryBalance; }
			set { this.carryBalance = value; }
		}

		[Property(Column="`Create_Date`")]
		public virtual DateTime CreateDate
		{
			get { return this.createDate; }
			set { this.createDate = value; }
		}

		[Property(Column="`Create_User_Id`")]
		public virtual int CreateUserId
		{
			get { return this.createUserId; }
			set { this.createUserId = value; }
		}

		[Property(Column="`Update_Date`")]
		public virtual DateTime? UpdateDate
		{
			get { return this.updateDate; }
			set { this.updateDate = value; }
		}

		[Property(Column="`Update_User_Id`")]
		public virtual string UpdateUserId
		{
			get { return this.updateUserId; }
			set { this.updateUserId = value; }
		}

		[Property(Column="`Deleted`")]
		public virtual bool Deleted
		{
			get { return this.deleted; }
			set { this.deleted = value; }
		}
		#endregion

		#region Methods

        public static ICriteria CreateCriteria()
        {
            using (ISession session = SqlSessionManager.OpenSession())
            {
                ICriteria c = session.CreateCriteria(typeof(DiscountRuleType));
                return c;
            }
        }

        public static List<DiscountRuleType> GetDiscountRuleTypeList(ICriteria criteria)
        {
            return (List<DiscountRuleType>)criteria.List<DiscountRuleType>();
        }

		public static DiscountRuleType GetDiscountRuleType(int discountRuleTypeId)
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				return session.Get<DiscountRuleType>(discountRuleTypeId);
			}
		}

		public static List<DiscountRuleType> GetDiscountRuleTypeList()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ICriteria c = session.CreateCriteria(typeof(DiscountRuleType));
				return (List<DiscountRuleType>)c.List<DiscountRuleType>();
			}
		}

		public static List<DiscountRuleType> GetDiscountRuleTypeList(string sortExpression, int maximumRows, int startRowIndex)
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ICriteria c = session.CreateCriteria(typeof(DiscountRuleType));
				if (sortExpression != null && sortExpression != "")
				{
					// Get ascending or descending order
					bool descending = sortExpression.Contains(" DESC");

					// Strip off ASC or DESC ordering
					sortExpression = sortExpression.Replace(" ASC", "");
					sortExpression = sortExpression.Replace(" DESC", "");
					sortExpression = sortExpression.Trim();

					// Get multi column sort from the comma delimited string
					List<String> expressions = new List<String>();
					if (sortExpression.Contains(","))
					{
						string[] tokens = sortExpression.Split(",".ToCharArray());
						for (int i = 0; i < tokens.Length; i++)
						{
							tokens[i] = tokens[i].Trim();
							if (tokens[i] != "")
								expressions.Add(tokens[i]);
						}
					}
					else if (sortExpression != "")
					{
						expressions.Add(sortExpression);
					}

					// Create the order
					for (int i = 0; i < expressions.Count; i++)
					{
						if (descending)
							c.AddOrder(NHibernate.Expression.Order.Desc(expressions[i]));
						else
							c.AddOrder(NHibernate.Expression.Order.Asc(expressions[i]));
					}
				}

				// Set offset and limit
				if (startRowIndex >= 0)
					c.SetFirstResult(startRowIndex);

				if (maximumRows >= 0)
					c.SetMaxResults(maximumRows);

				return (List<DiscountRuleType>)c.List<DiscountRuleType>();
			}
		}

		public static List<DiscountRuleType> GetDiscountRuleTypeList(string sortExpression)
		{
			return GetDiscountRuleTypeList(sortExpression, -1, -1);
		}

		public static void InsertDiscountRuleType(DiscountRuleType obj)
		{
			if (obj != null)
				obj.Insert();
		}

		public static void UpdateDiscountRuleType(DiscountRuleType obj)
		{
			if (obj != null)
				obj.Update();
		}

		public static void DeleteDiscountRuleType(DiscountRuleType obj)
		{
			if (obj != null)
				obj.Delete();
		}

        protected static DiscountRuleType PopulateDiscountRuleType(IDataReader r)
		{
			DiscountRuleType obj = new DiscountRuleType();
			obj.DiscountRuleTypeId = (int)r["Discount_Rule_Type_Id"];
			obj.Name = (string)r["Name"];
			obj.Description = (r["Description"] == DBNull.Value) ? null : (string)r["Description"];
			obj.MultiUseTF = (bool)r["Multi_Use_TF"];
			obj.MultiCustomerTF = (bool)r["Multi_Customer_TF"];
			obj.MultiOrderTF = (bool)r["Multi_Order_TF"];
			obj.CarryBalance = (bool)r["Carry_Balance"];
			obj.CreateDate = (DateTime)r["Create_Date"];
			obj.CreateUserId = (int)r["Create_User_Id"];
			obj.UpdateDate = (r["Update_Date"] == DBNull.Value) ? null : (DateTime?)r["Update_Date"];
			obj.UpdateUserId = (r["Update_User_Id"] == DBNull.Value) ? null : (string)r["Update_User_Id"];
			obj.Deleted = (bool)r["Deleted"];

			return obj;
		}

		public static int GetCount()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ICriteria c = session.CreateCriteria(typeof(DiscountRuleType));
				c.SetProjection(Projections.RowCount());
				return (int) c.UniqueResult();
			}
		}

		/// <summary>
		/// Insert the entity to database.
		/// </summary>
		public virtual void Insert()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ITransaction trans = session.BeginTransaction();
				try
				{
					session.Save(this);
					trans.Commit();
				}
				catch
				{
					trans.Rollback();
					throw;
				}
			}
		}

		/// <summary>
		/// Update the entity to database.
		/// </summary>
		public virtual void Update()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ITransaction trans = session.BeginTransaction();
				try
				{
					session.Update(this);
					trans.Commit();
				}
				catch
				{
					trans.Rollback();
					throw;
				}
			}
		}

		/// <summary>
		/// Persist the entity back to database.
		/// </summary>
		public virtual void Save()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ITransaction trans = session.BeginTransaction();
				try
				{
					session.SaveOrUpdate(this);
					trans.Commit();
				}
				catch
				{
					trans.Rollback();
					throw;
				}
			}
		}

		/// <summary>
		/// Delete entity in database.
		/// </summary>
		public virtual void Delete()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ITransaction trans = session.BeginTransaction();
				try
				{
					session.Delete(this);
					trans.Commit();
				}
				catch
				{
					trans.Rollback();
					throw;
				}
			}
		}

		/// <summary>
		/// Local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals(object obj)
		{
			if (this == obj)
				return true;

			if ((obj == null) || (obj.GetType() != this.GetType())) 
				return false;

			DiscountRuleType castObj = (DiscountRuleType)obj;
			return (castObj != null && this.discountRuleTypeId == castObj.DiscountRuleTypeId);
		}

		/// <summary>
		/// Local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			return 29 * (1 + this.discountRuleTypeId.GetHashCode());
		}
		#endregion
	}
}
