<?xml version="1.0" encoding="utf-8"?>
<Database Name="QSPFulfillment" Class="OrderExpressDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=uspvl3k09-dev;Initial Catalog=QSPFulfillment;User ID=QSPFormWebUser" SettingsObjectName="PostalAddressFix.Logic.Properties.Settings" SettingsPropertyName="QSPFulfillmentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.postal_address" Member="PostalAddresses">
    <Type Name="PostalAddress">
      <Column Name="postal_address_id" Member="PostalAddressId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="zip" Member="Zip" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="subdivision_code" Member="SubDivisionCode" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
    </Type>
  </Table>
</Database>