//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSP.OrderExpress.Web {
    
    
    public partial class OrderStep_DetailItem {
        
        /// <summary>
        /// Header control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QSP.OrderExpress.Web.UserControls.HeaderControl Header;
        
        /// <summary>
        /// ctrlOrderStep_DetailItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QSP.OrderExpress.Web.UserControls.OrderStep_DetailItem ctrlOrderStep_DetailItem;
    }
}
