<link REL="stylesheet" HREF="MagSysStyle.css" TYPE="text/css">
	<table BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="100%" BGCOLOR="#2f4f88">
			<tr height="5">
				<td></td>
			</tr>
	</table>

	<table border=0 cellpadding=1 cellspacing=0 WIDTH="100%" BGCOLOR="#878787" class=Font8v>
			<tr>
				<td>
					<table border=0 cellpadding=2 cellspacing=0 WIDTH="50%" BGCOLOR="#878787" class=Font8v>
								<tr>
									<td width=1></td>
									<td class=TopMenuItem>
										<a href='/PublisherDG.aspx'>Publishers</a>
									</td>
									<td class=TopMenuItem>
										<a href='/FulfillmentDG.aspx'>Fulfillment</a>
									</td>
									<td class=TopMenuItem>
										<a href='/MagazineDG.aspx'>Magazines</a>
									</td>
									<td class=TopMenuItem>
										<a href='/Reports/Reports.aspx'>Reports</a>
									</td>
									<td class=TopMenuItem>
										<a href='/default.aspx'>Home</a>
									</td>
									
									<td width=1></td>
								</tr>
					</table>
				</td>
				<td class=TopMenuItem align=right>
					<a href='/Logout.aspx'><font color=#CCCCCC></b>Logout</b></font></a>
				</td>
				<td width=5></td>
			</tr>
	</table>

	<table BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="100%" BGCOLOR="#2f4f88">
			<tr height="5">
				<td></td>
			</tr>
	</table>
	<p><p>