////////////////////////////////////////////////////////////////////////////////////////////
// Class generated by SqlCodeGen 1.1.0.0.
// Do not edit this file directly. Changes will be lost when this file is regenerated.
// Extensions should be added in a separate file using partial classes.
////////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Data;
using System.Text;
using NHibernate;
using NHibernate.Criterion;
using NHibernate.Mapping.Attributes;

namespace QSP.Business.Fulfillment
{
	[Serializable]
	[Class(Schema="`dbo`", Table="`form_section_type`")]
	public partial class FormSectionType
	{
		#region Constants
        public const string FormSectionTypeEntity = "FormSectionType";
		public const string FormSectionTypeIdProperty = "FormSectionTypeId";
		public const string FormSectionTypeNameProperty = "FormSectionTypeName";
		#endregion

		#region Fields
		protected int formSectionTypeId = 0;
		protected string formSectionTypeName = "";
		#endregion

		#region Constructors
		public FormSectionType() 
		{
		}
		#endregion

		#region Properties
		[RawXml(Content=@"
		<id name=""FormSectionTypeId"" column=""`form_section_type_id`"">
			<generator class=""assigned"">
			</generator>
		</id>")]

		public virtual int FormSectionTypeId
		{
			get { return this.formSectionTypeId; }
			set { this.formSectionTypeId = value; }
		}

		[Property(Column="`form_section_type_name`")]
		public virtual string FormSectionTypeName
		{
			get { return this.formSectionTypeName; }
			set { this.formSectionTypeName = value; }
		}
		#endregion

		#region Methods

        public static ICriteria CreateCriteria()
        {
            using (ISession session = SqlSessionManager.OpenSession())
            {
                ICriteria c = session.CreateCriteria(typeof(FormSectionType));
                return c;
            }
        }

        public static List<FormSectionType> GetFormSectionTypeList(ICriteria criteria)
        {
            return (List<FormSectionType>)criteria.List<FormSectionType>();
        }

		public static FormSectionType GetFormSectionType(int formSectionTypeId)
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				return session.Get<FormSectionType>(formSectionTypeId);
			}
		}

		public static List<FormSectionType> GetFormSectionTypeList()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ICriteria c = session.CreateCriteria(typeof(FormSectionType));
				return (List<FormSectionType>)c.List<FormSectionType>();
			}
		}

		public static List<FormSectionType> GetFormSectionTypeList(string sortExpression, int maximumRows, int startRowIndex)
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ICriteria c = session.CreateCriteria(typeof(FormSectionType));
				if (sortExpression != null && sortExpression != "")
				{
					// Get ascending or descending order
					bool descending = sortExpression.Contains(" DESC");

					// Strip off ASC or DESC ordering
					sortExpression = sortExpression.Replace(" ASC", "");
					sortExpression = sortExpression.Replace(" DESC", "");
					sortExpression = sortExpression.Trim();

					// Get multi column sort from the comma delimited string
					List<String> expressions = new List<String>();
					if (sortExpression.Contains(","))
					{
						string[] tokens = sortExpression.Split(",".ToCharArray());
						for (int i = 0; i < tokens.Length; i++)
						{
							tokens[i] = tokens[i].Trim();
							if (tokens[i] != "")
								expressions.Add(tokens[i]);
						}
					}
					else if (sortExpression != "")
					{
						expressions.Add(sortExpression);
					}

					// Create the order
					for (int i = 0; i < expressions.Count; i++)
					{
						if (descending)
							c.AddOrder(NHibernate.Criterion.Order.Desc(expressions[i]));
						else
							c.AddOrder(NHibernate.Criterion.Order.Asc(expressions[i]));
					}
				}

				// Set offset and limit
				if (startRowIndex >= 0)
					c.SetFirstResult(startRowIndex);

				if (maximumRows >= 0)
					c.SetMaxResults(maximumRows);

				return (List<FormSectionType>)c.List<FormSectionType>();
			}
		}

		public static List<FormSectionType> GetFormSectionTypeList(string sortExpression)
		{
			return GetFormSectionTypeList(sortExpression, -1, -1);
		}

		public static void InsertFormSectionType(FormSectionType obj)
		{
			if (obj != null)
				obj.Insert();
		}

		public static void UpdateFormSectionType(FormSectionType obj)
		{
			if (obj != null)
				obj.Update();
		}

		public static void DeleteFormSectionType(FormSectionType obj)
		{
			if (obj != null)
				obj.Delete();
		}

        protected static FormSectionType PopulateFormSectionType(IDataReader r)
		{
			FormSectionType obj = new FormSectionType();
			obj.FormSectionTypeId = (int)r["form_section_type_id"];
			obj.FormSectionTypeName = (string)r["form_section_type_name"];

			return obj;
		}

		public static int GetCount()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ICriteria c = session.CreateCriteria(typeof(FormSectionType));
				c.SetProjection(Projections.RowCount());
				return (int) c.UniqueResult();
			}
		}

		/// <summary>
		/// Insert the entity to database.
		/// </summary>
		public virtual void Insert()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ITransaction trans = session.BeginTransaction();
				try
				{
					session.Save(this);
					trans.Commit();
				}
				catch
				{
					trans.Rollback();
					throw;
				}
			}
		}

		/// <summary>
		/// Update the entity to database.
		/// </summary>
		public virtual void Update()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ITransaction trans = session.BeginTransaction();
				try
				{
					session.Update(this);
					trans.Commit();
				}
				catch
				{
					trans.Rollback();
					throw;
				}
			}
		}

		/// <summary>
		/// Delete entity in database.
		/// </summary>
		public virtual void Delete()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ITransaction trans = session.BeginTransaction();
				try
				{
					session.Delete(this);
					trans.Commit();
				}
				catch
				{
					trans.Rollback();
					throw;
				}
			}
		}

		/// <summary>
		/// Local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals(object obj)
		{
			if (this == obj)
				return true;

			if ((obj == null) || (obj.GetType() != this.GetType())) 
				return false;

			FormSectionType castObj = (FormSectionType)obj;
			return (castObj != null && this.formSectionTypeId == castObj.FormSectionTypeId);
		}

		/// <summary>
		/// Local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			return 29 * (1 + this.formSectionTypeId.GetHashCode());
		}
		#endregion
	}
}
