////////////////////////////////////////////////////////////////////////////////////////////
// Class generated by SqlCodeGen 1.1.0.0.
// Do not edit this file directly. Changes will be lost when this file is regenerated.
// Extensions should be added in a separate file using partial classes.
////////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Data;
using System.Text;
using NHibernate;
using NHibernate.Criterion;
using NHibernate.Mapping.Attributes;

namespace QSP.Business.Fulfillment
{
	[Serializable]
	[Class(Schema="`dbo`", Table="`warehouse_business_calendar`")]
	public partial class WarehouseBusinessCalendar
	{
		#region Constants
        public const string WarehouseBusinessCalendarEntity = "WarehouseBusinessCalendar";
		public const string WarehouseIdProperty = "WarehouseId";
		public const string BusinessDateProperty = "BusinessDate";
		public const string ClosedProperty = "Closed";
		#endregion

		#region Fields
		protected int warehouseId = 0;
		protected DateTime businessDate = DateTime.Now;
		protected bool closed = false;
		#endregion

		#region Constructors
		public WarehouseBusinessCalendar() 
		{
		}
		#endregion

		#region Properties
		[RawXml(Content=@"
		<composite-id>
			<key-property name=""WarehouseId"" column=""`warehouse_id`"" />
			<key-property name=""BusinessDate"" column=""`business_date`"" />
		</composite-id>")]

		public virtual int WarehouseId
		{
			get { return this.warehouseId; }
			set { this.warehouseId = value; }
		}

		public virtual DateTime BusinessDate
		{
			get { return this.businessDate; }
			set { this.businessDate = value; }
		}

		[Property(Column="`closed`")]
		public virtual bool Closed
		{
			get { return this.closed; }
			set { this.closed = value; }
		}
		#endregion

		#region Methods

        public static ICriteria CreateCriteria()
        {
            using (ISession session = SqlSessionManager.OpenSession())
            {
                ICriteria c = session.CreateCriteria(typeof(WarehouseBusinessCalendar));
                return c;
            }
        }

        public static List<WarehouseBusinessCalendar> GetWarehouseBusinessCalendarList(ICriteria criteria)
        {
            return (List<WarehouseBusinessCalendar>)criteria.List<WarehouseBusinessCalendar>();
        }

		public static WarehouseBusinessCalendar GetWarehouseBusinessCalendar(int warehouseId, DateTime businessDate)
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ICriteria c = session.CreateCriteria(typeof(WarehouseBusinessCalendar));
				c.Add(Expression.Eq(WarehouseIdProperty, warehouseId));
				c.Add(Expression.Eq(BusinessDateProperty, businessDate));
				return c.UniqueResult<WarehouseBusinessCalendar>();
			}
		}

		public static List<WarehouseBusinessCalendar> GetWarehouseBusinessCalendarList()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ICriteria c = session.CreateCriteria(typeof(WarehouseBusinessCalendar));
				return (List<WarehouseBusinessCalendar>)c.List<WarehouseBusinessCalendar>();
			}
		}

		public static List<WarehouseBusinessCalendar> GetWarehouseBusinessCalendarList(string sortExpression, int maximumRows, int startRowIndex)
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ICriteria c = session.CreateCriteria(typeof(WarehouseBusinessCalendar));
				if (sortExpression != null && sortExpression != "")
				{
					// Get ascending or descending order
					bool descending = sortExpression.Contains(" DESC");

					// Strip off ASC or DESC ordering
					sortExpression = sortExpression.Replace(" ASC", "");
					sortExpression = sortExpression.Replace(" DESC", "");
					sortExpression = sortExpression.Trim();

					// Get multi column sort from the comma delimited string
					List<String> expressions = new List<String>();
					if (sortExpression.Contains(","))
					{
						string[] tokens = sortExpression.Split(",".ToCharArray());
						for (int i = 0; i < tokens.Length; i++)
						{
							tokens[i] = tokens[i].Trim();
							if (tokens[i] != "")
								expressions.Add(tokens[i]);
						}
					}
					else if (sortExpression != "")
					{
						expressions.Add(sortExpression);
					}

					// Create the order
					for (int i = 0; i < expressions.Count; i++)
					{
						if (descending)
							c.AddOrder(NHibernate.Criterion.Order.Desc(expressions[i]));
						else
							c.AddOrder(NHibernate.Criterion.Order.Asc(expressions[i]));
					}
				}

				// Set offset and limit
				if (startRowIndex >= 0)
					c.SetFirstResult(startRowIndex);

				if (maximumRows >= 0)
					c.SetMaxResults(maximumRows);

				return (List<WarehouseBusinessCalendar>)c.List<WarehouseBusinessCalendar>();
			}
		}

		public static List<WarehouseBusinessCalendar> GetWarehouseBusinessCalendarList(string sortExpression)
		{
			return GetWarehouseBusinessCalendarList(sortExpression, -1, -1);
		}

		public static void InsertWarehouseBusinessCalendar(WarehouseBusinessCalendar obj)
		{
			if (obj != null)
				obj.Insert();
		}

		public static void UpdateWarehouseBusinessCalendar(WarehouseBusinessCalendar obj)
		{
			if (obj != null)
				obj.Update();
		}

		public static void DeleteWarehouseBusinessCalendar(WarehouseBusinessCalendar obj)
		{
			if (obj != null)
				obj.Delete();
		}

        protected static WarehouseBusinessCalendar PopulateWarehouseBusinessCalendar(IDataReader r)
		{
			WarehouseBusinessCalendar obj = new WarehouseBusinessCalendar();
			obj.WarehouseId = (int)r["warehouse_id"];
			obj.BusinessDate = (DateTime)r["business_date"];
			obj.Closed = (bool)r["closed"];

			return obj;
		}

		public static int GetCount()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ICriteria c = session.CreateCriteria(typeof(WarehouseBusinessCalendar));
				c.SetProjection(Projections.RowCount());
				return (int) c.UniqueResult();
			}
		}

		/// <summary>
		/// Insert the entity to database.
		/// </summary>
		public virtual void Insert()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ITransaction trans = session.BeginTransaction();
				try
				{
					session.Save(this);
					trans.Commit();
				}
				catch
				{
					trans.Rollback();
					throw;
				}
			}
		}

		/// <summary>
		/// Update the entity to database.
		/// </summary>
		public virtual void Update()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ITransaction trans = session.BeginTransaction();
				try
				{
					session.Update(this);
					trans.Commit();
				}
				catch
				{
					trans.Rollback();
					throw;
				}
			}
		}

		/// <summary>
		/// Delete entity in database.
		/// </summary>
		public virtual void Delete()
		{
			using (ISession session = SqlSessionManager.OpenSession())
			{
				ITransaction trans = session.BeginTransaction();
				try
				{
					session.Delete(this);
					trans.Commit();
				}
				catch
				{
					trans.Rollback();
					throw;
				}
			}
		}

		/// <summary>
		/// Local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals(object obj)
		{
			if (this == obj)
				return true;

			if ((obj == null) || (obj.GetType() != this.GetType())) 
				return false;

			WarehouseBusinessCalendar castObj = (WarehouseBusinessCalendar)obj;
			return (castObj != null && this.warehouseId == castObj.WarehouseId && this.businessDate == castObj.BusinessDate);
		}

		/// <summary>
		/// Local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			return 29 * (1 + this.warehouseId.GetHashCode() + this.businessDate.GetHashCode());
		}
		#endregion
	}
}
