//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Data
{
    
    public partial class ParticipantNode : INotifyComplexPropertyChanging, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public string FIRSTNAME
        {
            get { return _fIRSTNAME; }
            set
            {
                if (_fIRSTNAME != value)
                {
                    OnComplexPropertyChanging();
                    _fIRSTNAME = value;
                    OnPropertyChanged("FIRSTNAME");
                }
            }
        }
        private string _fIRSTNAME;
    
        [DataMember]
        public string MIDDLEINITIAL
        {
            get { return _mIDDLEINITIAL; }
            set
            {
                if (_mIDDLEINITIAL != value)
                {
                    OnComplexPropertyChanging();
                    _mIDDLEINITIAL = value;
                    OnPropertyChanged("MIDDLEINITIAL");
                }
            }
        }
        private string _mIDDLEINITIAL;
    
        [DataMember]
        public string LASTNAME
        {
            get { return _lASTNAME; }
            set
            {
                if (_lASTNAME != value)
                {
                    OnComplexPropertyChanging();
                    _lASTNAME = value;
                    OnPropertyChanged("LASTNAME");
                }
            }
        }
        private string _lASTNAME;

        #endregion
        #region ChangeTracking
    
        private void OnComplexPropertyChanging()
        {
            if (_complexPropertyChanging != null)
            {
                _complexPropertyChanging(this, new EventArgs());
            }
        }
    
        event EventHandler INotifyComplexPropertyChanging.ComplexPropertyChanging { add { _complexPropertyChanging += value; } remove { _complexPropertyChanging -= value; } }
        private event EventHandler _complexPropertyChanging;
    
        private void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged { add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        public static void RecordComplexOriginalValues(String parentPropertyName, ParticipantNode complexObject, ObjectChangeTracker changeTracker)
        {
            if (String.IsNullOrEmpty(parentPropertyName))
            {
                throw new ArgumentException("String parameter cannot be null or empty.", "parentPropertyName");
            }
    
            if (changeTracker == null)
            {
                throw new ArgumentNullException("changeTracker");
            }
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.FIRSTNAME", parentPropertyName), complexObject == null ? null : (object)complexObject.FIRSTNAME);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.MIDDLEINITIAL", parentPropertyName), complexObject == null ? null : (object)complexObject.MIDDLEINITIAL);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.LASTNAME", parentPropertyName), complexObject == null ? null : (object)complexObject.LASTNAME);
        }

        #endregion
    }
}
