<%
' This file was generated from the WebBuild database.
' Consumer: ATC Web sites.
Call EmitOneStateOption("AK", "Alaska", sValue)
Call EmitOneStateOption("AL", "Alabama", sValue)
Call EmitOneStateOption("AZ", "Arizona", sValue)
Call EmitOneStateOption("AR", "Arkansas", sValue)
Call EmitOneStateOption("CA", "California", sValue)
Call EmitOneStateOption("CO", "Colorado", sValue)
Call EmitOneStateOption("CT", "Connecticut", sValue)
Call EmitOneStateOption("DE", "Delaware", sValue)
Call EmitOneStateOption("FL", "Florida", sValue)
Call EmitOneStateOption("GA", "Georgia", sValue)
Call EmitOneStateOption("GU", "Guam", sValue)
Call EmitOneStateOption("HI", "Hawaii", sValue)
Call EmitOneStateOption("ID", "Idaho", sValue)
Call EmitOneStateOption("IL", "Illinois", sValue)
Call EmitOneStateOption("IN", "Indiana", sValue)
Call EmitOneStateOption("IA", "Iowa", sValue)
Call EmitOneStateOption("KS", "Kansas", sValue)
Call EmitOneStateOption("KY", "Kentucky", sValue)
Call EmitOneStateOption("LA", "Louisiana", sValue)
Call EmitOneStateOption("ME", "Maine", sValue)
Call EmitOneStateOption("MD", "Maryland", sValue)
Call EmitOneStateOption("MA", "Massachusetts", sValue)
Call EmitOneStateOption("MI", "Michigan", sValue)
Call EmitOneStateOption("MN", "Minnesota", sValue)
Call EmitOneStateOption("MS", "Mississippi", sValue)
Call EmitOneStateOption("MO", "Missouri", sValue)
Call EmitOneStateOption("MT", "Montana", sValue)
Call EmitOneStateOption("NE", "Nebraska", sValue)
Call EmitOneStateOption("NV", "Nevada", sValue)
Call EmitOneStateOption("NH", "New Hampshire", sValue)
Call EmitOneStateOption("NJ", "New Jersey", sValue)
Call EmitOneStateOption("NM", "New Mexico", sValue)
Call EmitOneStateOption("NY", "New York", sValue)
Call EmitOneStateOption("NC", "North Carolina", sValue)
Call EmitOneStateOption("ND", "North Dakota", sValue)
Call EmitOneStateOption("OH", "Ohio", sValue)
Call EmitOneStateOption("OK", "Oklahoma", sValue)
Call EmitOneStateOption("OR", "Oregon", sValue)
Call EmitOneStateOption("PA", "Pennsylvania", sValue)
Call EmitOneStateOption("RI", "Rhode Island", sValue)
Call EmitOneStateOption("SC", "South Carolina", sValue)
Call EmitOneStateOption("SD", "South Dakota", sValue)
Call EmitOneStateOption("TN", "Tennessee", sValue)
Call EmitOneStateOption("TX", "Texas", sValue)
Call EmitOneStateOption("UT", "Utah", sValue)
Call EmitOneStateOption("VT", "Vermont", sValue)
Call EmitOneStateOption("VA", "Virginia", sValue)
Call EmitOneStateOption("WA", "Washington", sValue)
Call EmitOneStateOption("DC", "Washington, D.C.", sValue)
Call EmitOneStateOption("WV", "West Virginia", sValue)
Call EmitOneStateOption("WI", "Wisconsin", sValue)
Call EmitOneStateOption("WY", "Wyoming", sValue)
Call EmitOneStateOption("AA", "Armed Forces the Americas", sValue)
Call EmitOneStateOption("AE", "Armed Forces Europe", sValue)
Call EmitOneStateOption("AP", "Armed Forces Pacific", sValue)
%>