#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GA.BDC.Core.Database.EFRLinqToSQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EFRCommon")]
	public partial class EFRCommonDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertpartner(partner instance);
    partial void Updatepartner(partner instance);
    partial void Deletepartner(partner instance);
    partial void Insertpartner_attribute(partner_attribute instance);
    partial void Updatepartner_attribute(partner_attribute instance);
    partial void Deletepartner_attribute(partner_attribute instance);
    partial void Insertpartner_attribute_value(partner_attribute_value instance);
    partial void Updatepartner_attribute_value(partner_attribute_value instance);
    partial void Deletepartner_attribute_value(partner_attribute_value instance);
    partial void Insertpartner_promotion(partner_promotion instance);
    partial void Updatepartner_promotion(partner_promotion instance);
    partial void Deletepartner_promotion(partner_promotion instance);
    #endregion
		
		public EFRCommonDataContext() : 
				base(global::GA.BDC.Core.Database.EFRLinqToSQL.Properties.Settings.Default.EFRCommonConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public EFRCommonDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EFRCommonDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EFRCommonDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EFRCommonDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<partner> partners
		{
			get
			{
				return this.GetTable<partner>();
			}
		}
		
		public System.Data.Linq.Table<partner_attribute> partner_attributes
		{
			get
			{
				return this.GetTable<partner_attribute>();
			}
		}
		
		public System.Data.Linq.Table<partner_attribute_value> partner_attribute_values
		{
			get
			{
				return this.GetTable<partner_attribute_value>();
			}
		}
		
		public System.Data.Linq.Table<partner_promotion> partner_promotions
		{
			get
			{
				return this.GetTable<partner_promotion>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.efrc_get_partner_by_aaid")]
		public ISingleResult<efrc_get_partner_by_aaidResult> efrc_get_partner_by_aaid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string a_aid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), a_aid);
			return ((ISingleResult<efrc_get_partner_by_aaidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.efrc_get_partner_by_id")]
		public ISingleResult<efrc_get_partner_by_idResult> efrc_get_partner_by_id([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> partnerID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), partnerID);
			return ((ISingleResult<efrc_get_partner_by_idResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.efrc_get_partners")]
		public ISingleResult<efrc_get_partnersResult> efrc_get_partners()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<efrc_get_partnersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.efrc_get_profit_by_id")]
		public ISingleResult<efrc_get_profit_by_idResult> efrc_get_profit_by_id([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> profit_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), profit_id);
			return ((ISingleResult<efrc_get_profit_by_idResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.es_get_partner_attributes")]
		public ISingleResult<es_get_partner_attributesResult> es_get_partner_attributes([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> partnerID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cultureCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), partnerID, cultureCode);
			return ((ISingleResult<es_get_partner_attributesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.efrc_get_partner_personalization")]
		public ISingleResult<efrc_get_partner_personalizationResult> efrc_get_partner_personalization([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> partner_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(5)")] string culture_code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), partner_id, culture_code);
			return ((ISingleResult<efrc_get_partner_personalizationResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.partner")]
	public partial class partner : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _partner_id;
		
		private int _partner_type_id;
		
		private string _partner_name;
		
		private bool _has_collection_site;
		
		private System.Guid _guid;
		
		private System.DateTime _create_date;
		
		private bool _is_active;
		
		private EntitySet<partner_attribute_value> _partner_attribute_values;
		
		private EntitySet<partner_promotion> _partner_promotions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpartner_idChanging(int value);
    partial void Onpartner_idChanged();
    partial void Onpartner_type_idChanging(int value);
    partial void Onpartner_type_idChanged();
    partial void Onpartner_nameChanging(string value);
    partial void Onpartner_nameChanged();
    partial void Onhas_collection_siteChanging(bool value);
    partial void Onhas_collection_siteChanged();
    partial void OnguidChanging(System.Guid value);
    partial void OnguidChanged();
    partial void Oncreate_dateChanging(System.DateTime value);
    partial void Oncreate_dateChanged();
    partial void Onis_activeChanging(bool value);
    partial void Onis_activeChanged();
    #endregion
		
		public partner()
		{
			this._partner_attribute_values = new EntitySet<partner_attribute_value>(new Action<partner_attribute_value>(this.attach_partner_attribute_values), new Action<partner_attribute_value>(this.detach_partner_attribute_values));
			this._partner_promotions = new EntitySet<partner_promotion>(new Action<partner_promotion>(this.attach_partner_promotions), new Action<partner_promotion>(this.detach_partner_promotions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int partner_id
		{
			get
			{
				return this._partner_id;
			}
			set
			{
				if ((this._partner_id != value))
				{
					this.Onpartner_idChanging(value);
					this.SendPropertyChanging();
					this._partner_id = value;
					this.SendPropertyChanged("partner_id");
					this.Onpartner_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_type_id", DbType="Int NOT NULL")]
		public int partner_type_id
		{
			get
			{
				return this._partner_type_id;
			}
			set
			{
				if ((this._partner_type_id != value))
				{
					this.Onpartner_type_idChanging(value);
					this.SendPropertyChanging();
					this._partner_type_id = value;
					this.SendPropertyChanged("partner_type_id");
					this.Onpartner_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string partner_name
		{
			get
			{
				return this._partner_name;
			}
			set
			{
				if ((this._partner_name != value))
				{
					this.Onpartner_nameChanging(value);
					this.SendPropertyChanging();
					this._partner_name = value;
					this.SendPropertyChanged("partner_name");
					this.Onpartner_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_collection_site", DbType="Bit NOT NULL")]
		public bool has_collection_site
		{
			get
			{
				return this._has_collection_site;
			}
			set
			{
				if ((this._has_collection_site != value))
				{
					this.Onhas_collection_siteChanging(value);
					this.SendPropertyChanging();
					this._has_collection_site = value;
					this.SendPropertyChanged("has_collection_site");
					this.Onhas_collection_siteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid guid
		{
			get
			{
				return this._guid;
			}
			set
			{
				if ((this._guid != value))
				{
					this.OnguidChanging(value);
					this.SendPropertyChanging();
					this._guid = value;
					this.SendPropertyChanged("guid");
					this.OnguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_active", DbType="Bit NOT NULL")]
		public bool is_active
		{
			get
			{
				return this._is_active;
			}
			set
			{
				if ((this._is_active != value))
				{
					this.Onis_activeChanging(value);
					this.SendPropertyChanging();
					this._is_active = value;
					this.SendPropertyChanged("is_active");
					this.Onis_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="partner_partner_attribute_value", Storage="_partner_attribute_values", ThisKey="partner_id", OtherKey="partner_id")]
		public EntitySet<partner_attribute_value> partner_attribute_values
		{
			get
			{
				return this._partner_attribute_values;
			}
			set
			{
				this._partner_attribute_values.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="partner_partner_promotion", Storage="_partner_promotions", ThisKey="partner_id", OtherKey="partner_id")]
		public EntitySet<partner_promotion> partner_promotions
		{
			get
			{
				return this._partner_promotions;
			}
			set
			{
				this._partner_promotions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_partner_attribute_values(partner_attribute_value entity)
		{
			this.SendPropertyChanging();
			entity.partner = this;
		}
		
		private void detach_partner_attribute_values(partner_attribute_value entity)
		{
			this.SendPropertyChanging();
			entity.partner = null;
		}
		
		private void attach_partner_promotions(partner_promotion entity)
		{
			this.SendPropertyChanging();
			entity.partner = this;
		}
		
		private void detach_partner_promotions(partner_promotion entity)
		{
			this.SendPropertyChanging();
			entity.partner = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.partner_attribute")]
	public partial class partner_attribute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _partner_attribute_id;
		
		private string _partner_attribute_name;
		
		private System.DateTime _create_date;
		
		private EntitySet<partner_attribute_value> _partner_attribute_values;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpartner_attribute_idChanging(int value);
    partial void Onpartner_attribute_idChanged();
    partial void Onpartner_attribute_nameChanging(string value);
    partial void Onpartner_attribute_nameChanged();
    partial void Oncreate_dateChanging(System.DateTime value);
    partial void Oncreate_dateChanged();
    #endregion
		
		public partner_attribute()
		{
			this._partner_attribute_values = new EntitySet<partner_attribute_value>(new Action<partner_attribute_value>(this.attach_partner_attribute_values), new Action<partner_attribute_value>(this.detach_partner_attribute_values));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_attribute_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int partner_attribute_id
		{
			get
			{
				return this._partner_attribute_id;
			}
			set
			{
				if ((this._partner_attribute_id != value))
				{
					this.Onpartner_attribute_idChanging(value);
					this.SendPropertyChanging();
					this._partner_attribute_id = value;
					this.SendPropertyChanged("partner_attribute_id");
					this.Onpartner_attribute_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_attribute_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string partner_attribute_name
		{
			get
			{
				return this._partner_attribute_name;
			}
			set
			{
				if ((this._partner_attribute_name != value))
				{
					this.Onpartner_attribute_nameChanging(value);
					this.SendPropertyChanging();
					this._partner_attribute_name = value;
					this.SendPropertyChanged("partner_attribute_name");
					this.Onpartner_attribute_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="partner_attribute_partner_attribute_value", Storage="_partner_attribute_values", ThisKey="partner_attribute_id", OtherKey="partner_attribute_id")]
		public EntitySet<partner_attribute_value> partner_attribute_values
		{
			get
			{
				return this._partner_attribute_values;
			}
			set
			{
				this._partner_attribute_values.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_partner_attribute_values(partner_attribute_value entity)
		{
			this.SendPropertyChanging();
			entity.partner_attribute = this;
		}
		
		private void detach_partner_attribute_values(partner_attribute_value entity)
		{
			this.SendPropertyChanging();
			entity.partner_attribute = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.partner_attribute_value")]
	public partial class partner_attribute_value : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _partner_id;
		
		private int _partner_attribute_id;
		
		private string _culture_code;
		
		private string _value;
		
		private System.DateTime _create_date;
		
		private EntityRef<partner> _partner;
		
		private EntityRef<partner_attribute> _partner_attribute;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpartner_idChanging(int value);
    partial void Onpartner_idChanged();
    partial void Onpartner_attribute_idChanging(int value);
    partial void Onpartner_attribute_idChanged();
    partial void Onculture_codeChanging(string value);
    partial void Onculture_codeChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    partial void Oncreate_dateChanging(System.DateTime value);
    partial void Oncreate_dateChanged();
    #endregion
		
		public partner_attribute_value()
		{
			this._partner = default(EntityRef<partner>);
			this._partner_attribute = default(EntityRef<partner_attribute>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int partner_id
		{
			get
			{
				return this._partner_id;
			}
			set
			{
				if ((this._partner_id != value))
				{
					if (this._partner.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpartner_idChanging(value);
					this.SendPropertyChanging();
					this._partner_id = value;
					this.SendPropertyChanged("partner_id");
					this.Onpartner_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_attribute_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int partner_attribute_id
		{
			get
			{
				return this._partner_attribute_id;
			}
			set
			{
				if ((this._partner_attribute_id != value))
				{
					if (this._partner_attribute.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpartner_attribute_idChanging(value);
					this.SendPropertyChanging();
					this._partner_attribute_id = value;
					this.SendPropertyChanged("partner_attribute_id");
					this.Onpartner_attribute_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_culture_code", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string culture_code
		{
			get
			{
				return this._culture_code;
			}
			set
			{
				if ((this._culture_code != value))
				{
					this.Onculture_codeChanging(value);
					this.SendPropertyChanging();
					this._culture_code = value;
					this.SendPropertyChanged("culture_code");
					this.Onculture_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="partner_partner_attribute_value", Storage="_partner", ThisKey="partner_id", OtherKey="partner_id", IsForeignKey=true)]
		public partner partner
		{
			get
			{
				return this._partner.Entity;
			}
			set
			{
				partner previousValue = this._partner.Entity;
				if (((previousValue != value) 
							|| (this._partner.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._partner.Entity = null;
						previousValue.partner_attribute_values.Remove(this);
					}
					this._partner.Entity = value;
					if ((value != null))
					{
						value.partner_attribute_values.Add(this);
						this._partner_id = value.partner_id;
					}
					else
					{
						this._partner_id = default(int);
					}
					this.SendPropertyChanged("partner");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="partner_attribute_partner_attribute_value", Storage="_partner_attribute", ThisKey="partner_attribute_id", OtherKey="partner_attribute_id", IsForeignKey=true)]
		public partner_attribute partner_attribute
		{
			get
			{
				return this._partner_attribute.Entity;
			}
			set
			{
				partner_attribute previousValue = this._partner_attribute.Entity;
				if (((previousValue != value) 
							|| (this._partner_attribute.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._partner_attribute.Entity = null;
						previousValue.partner_attribute_values.Remove(this);
					}
					this._partner_attribute.Entity = value;
					if ((value != null))
					{
						value.partner_attribute_values.Add(this);
						this._partner_attribute_id = value.partner_attribute_id;
					}
					else
					{
						this._partner_attribute_id = default(int);
					}
					this.SendPropertyChanged("partner_attribute");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.partner_promotion")]
	public partial class partner_promotion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _partner_promotion_id;
		
		private int _partner_id;
		
		private int _promotion_id;
		
		private System.DateTime _create_date;
		
		private EntityRef<partner> _partner;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpartner_promotion_idChanging(int value);
    partial void Onpartner_promotion_idChanged();
    partial void Onpartner_idChanging(int value);
    partial void Onpartner_idChanged();
    partial void Onpromotion_idChanging(int value);
    partial void Onpromotion_idChanged();
    partial void Oncreate_dateChanging(System.DateTime value);
    partial void Oncreate_dateChanged();
    #endregion
		
		public partner_promotion()
		{
			this._partner = default(EntityRef<partner>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_promotion_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int partner_promotion_id
		{
			get
			{
				return this._partner_promotion_id;
			}
			set
			{
				if ((this._partner_promotion_id != value))
				{
					this.Onpartner_promotion_idChanging(value);
					this.SendPropertyChanging();
					this._partner_promotion_id = value;
					this.SendPropertyChanged("partner_promotion_id");
					this.Onpartner_promotion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_id", DbType="Int NOT NULL")]
		public int partner_id
		{
			get
			{
				return this._partner_id;
			}
			set
			{
				if ((this._partner_id != value))
				{
					if (this._partner.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpartner_idChanging(value);
					this.SendPropertyChanging();
					this._partner_id = value;
					this.SendPropertyChanged("partner_id");
					this.Onpartner_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_promotion_id", DbType="Int NOT NULL")]
		public int promotion_id
		{
			get
			{
				return this._promotion_id;
			}
			set
			{
				if ((this._promotion_id != value))
				{
					this.Onpromotion_idChanging(value);
					this.SendPropertyChanging();
					this._promotion_id = value;
					this.SendPropertyChanged("promotion_id");
					this.Onpromotion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="partner_partner_promotion", Storage="_partner", ThisKey="partner_id", OtherKey="partner_id", IsForeignKey=true)]
		public partner partner
		{
			get
			{
				return this._partner.Entity;
			}
			set
			{
				partner previousValue = this._partner.Entity;
				if (((previousValue != value) 
							|| (this._partner.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._partner.Entity = null;
						previousValue.partner_promotions.Remove(this);
					}
					this._partner.Entity = value;
					if ((value != null))
					{
						value.partner_promotions.Add(this);
						this._partner_id = value.partner_id;
					}
					else
					{
						this._partner_id = default(int);
					}
					this.SendPropertyChanged("partner");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class efrc_get_partner_by_aaidResult
	{
		
		private int _partner_id;
		
		private int _partner_type_id;
		
		private string _partner_name;
		
		private bool _has_collection_site;
		
		private System.Guid _guid;
		
		private string _partner_type_name;
		
		public efrc_get_partner_by_aaidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_id", DbType="Int NOT NULL")]
		public int partner_id
		{
			get
			{
				return this._partner_id;
			}
			set
			{
				if ((this._partner_id != value))
				{
					this._partner_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_type_id", DbType="Int NOT NULL")]
		public int partner_type_id
		{
			get
			{
				return this._partner_type_id;
			}
			set
			{
				if ((this._partner_type_id != value))
				{
					this._partner_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string partner_name
		{
			get
			{
				return this._partner_name;
			}
			set
			{
				if ((this._partner_name != value))
				{
					this._partner_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_collection_site", DbType="Bit NOT NULL")]
		public bool has_collection_site
		{
			get
			{
				return this._has_collection_site;
			}
			set
			{
				if ((this._has_collection_site != value))
				{
					this._has_collection_site = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid guid
		{
			get
			{
				return this._guid;
			}
			set
			{
				if ((this._guid != value))
				{
					this._guid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_type_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string partner_type_name
		{
			get
			{
				return this._partner_type_name;
			}
			set
			{
				if ((this._partner_type_name != value))
				{
					this._partner_type_name = value;
				}
			}
		}
	}
	
	public partial class efrc_get_partner_by_idResult
	{
		
		private int _partner_id;
		
		private int _partner_type_id;
		
		private string _partner_name;
		
		private bool _has_collection_site;
		
		private System.Guid _guid;
		
		private string _partner_type_name;
		
		public efrc_get_partner_by_idResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_id", DbType="Int NOT NULL")]
		public int partner_id
		{
			get
			{
				return this._partner_id;
			}
			set
			{
				if ((this._partner_id != value))
				{
					this._partner_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_type_id", DbType="Int NOT NULL")]
		public int partner_type_id
		{
			get
			{
				return this._partner_type_id;
			}
			set
			{
				if ((this._partner_type_id != value))
				{
					this._partner_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string partner_name
		{
			get
			{
				return this._partner_name;
			}
			set
			{
				if ((this._partner_name != value))
				{
					this._partner_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_collection_site", DbType="Bit NOT NULL")]
		public bool has_collection_site
		{
			get
			{
				return this._has_collection_site;
			}
			set
			{
				if ((this._has_collection_site != value))
				{
					this._has_collection_site = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid guid
		{
			get
			{
				return this._guid;
			}
			set
			{
				if ((this._guid != value))
				{
					this._guid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_type_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string partner_type_name
		{
			get
			{
				return this._partner_type_name;
			}
			set
			{
				if ((this._partner_type_name != value))
				{
					this._partner_type_name = value;
				}
			}
		}
	}
	
	public partial class efrc_get_partnersResult
	{
		
		private int _partner_id;
		
		private int _partner_type_id;
		
		private string _partner_name;
		
		private bool _has_collection_site;
		
		private System.Guid _guid;
		
		private string _partner_type_name;
		
		public efrc_get_partnersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_id", DbType="Int NOT NULL")]
		public int partner_id
		{
			get
			{
				return this._partner_id;
			}
			set
			{
				if ((this._partner_id != value))
				{
					this._partner_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_type_id", DbType="Int NOT NULL")]
		public int partner_type_id
		{
			get
			{
				return this._partner_type_id;
			}
			set
			{
				if ((this._partner_type_id != value))
				{
					this._partner_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string partner_name
		{
			get
			{
				return this._partner_name;
			}
			set
			{
				if ((this._partner_name != value))
				{
					this._partner_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_collection_site", DbType="Bit NOT NULL")]
		public bool has_collection_site
		{
			get
			{
				return this._has_collection_site;
			}
			set
			{
				if ((this._has_collection_site != value))
				{
					this._has_collection_site = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid guid
		{
			get
			{
				return this._guid;
			}
			set
			{
				if ((this._guid != value))
				{
					this._guid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_type_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string partner_type_name
		{
			get
			{
				return this._partner_type_name;
			}
			set
			{
				if ((this._partner_type_name != value))
				{
					this._partner_type_name = value;
				}
			}
		}
	}
	
	public partial class efrc_get_profit_by_idResult
	{
		
		private int _profit_id;
		
		private double _profit_percentage;
		
		private string _description;
		
		private string _disclaimer;
		
		private string _alt_disclaimer;
		
		private System.Nullable<int> _profit_group_id;
		
		private System.Nullable<int> _qsp_catalog_type_id;
		
		public efrc_get_profit_by_idResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profit_id", DbType="Int NOT NULL")]
		public int profit_id
		{
			get
			{
				return this._profit_id;
			}
			set
			{
				if ((this._profit_id != value))
				{
					this._profit_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profit_percentage", DbType="Float NOT NULL")]
		public double profit_percentage
		{
			get
			{
				return this._profit_percentage;
			}
			set
			{
				if ((this._profit_percentage != value))
				{
					this._profit_percentage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(50)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_disclaimer", DbType="VarChar(500)")]
		public string disclaimer
		{
			get
			{
				return this._disclaimer;
			}
			set
			{
				if ((this._disclaimer != value))
				{
					this._disclaimer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alt_disclaimer", DbType="VarChar(500)")]
		public string alt_disclaimer
		{
			get
			{
				return this._alt_disclaimer;
			}
			set
			{
				if ((this._alt_disclaimer != value))
				{
					this._alt_disclaimer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profit_group_id", DbType="Int")]
		public System.Nullable<int> profit_group_id
		{
			get
			{
				return this._profit_group_id;
			}
			set
			{
				if ((this._profit_group_id != value))
				{
					this._profit_group_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qsp_catalog_type_id", DbType="Int")]
		public System.Nullable<int> qsp_catalog_type_id
		{
			get
			{
				return this._qsp_catalog_type_id;
			}
			set
			{
				if ((this._qsp_catalog_type_id != value))
				{
					this._qsp_catalog_type_id = value;
				}
			}
		}
	}
	
	public partial class es_get_partner_attributesResult
	{
		
		private int _partner_attribute_id;
		
		private string _partner_attribute_name;
		
		private string _culture_code;
		
		private string _value;
		
		public es_get_partner_attributesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_attribute_id", DbType="Int NOT NULL")]
		public int partner_attribute_id
		{
			get
			{
				return this._partner_attribute_id;
			}
			set
			{
				if ((this._partner_attribute_id != value))
				{
					this._partner_attribute_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_attribute_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string partner_attribute_name
		{
			get
			{
				return this._partner_attribute_name;
			}
			set
			{
				if ((this._partner_attribute_name != value))
				{
					this._partner_attribute_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_culture_code", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string culture_code
		{
			get
			{
				return this._culture_code;
			}
			set
			{
				if ((this._culture_code != value))
				{
					this._culture_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this._value = value;
				}
			}
		}
	}
	
	public partial class efrc_get_partner_personalizationResult
	{
		
		private string _partner_name;
		
		private string _partner_url;
		
		private string _phone_number;
		
		private string _email_address;
		
		private string _fax;
		
		private string _mailing_address;
		
		private string _partner_path;
		
		private string _partner_folder;
		
		private string _partner_banner_image;
		
		private string _partner_bottom_banner_image;
		
		private string _partner_top_link;
		
		private string _partner_bottom_link;
		
		private string _kit_banner_image;
		
		public efrc_get_partner_personalizationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_name", DbType="VarChar(255)")]
		public string partner_name
		{
			get
			{
				return this._partner_name;
			}
			set
			{
				if ((this._partner_name != value))
				{
					this._partner_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_url", DbType="VarChar(255)")]
		public string partner_url
		{
			get
			{
				return this._partner_url;
			}
			set
			{
				if ((this._partner_url != value))
				{
					this._partner_url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(255)")]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this._phone_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_address", DbType="VarChar(255)")]
		public string email_address
		{
			get
			{
				return this._email_address;
			}
			set
			{
				if ((this._email_address != value))
				{
					this._email_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(255)")]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this._fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mailing_address", DbType="VarChar(255)")]
		public string mailing_address
		{
			get
			{
				return this._mailing_address;
			}
			set
			{
				if ((this._mailing_address != value))
				{
					this._mailing_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_path", DbType="VarChar(255)")]
		public string partner_path
		{
			get
			{
				return this._partner_path;
			}
			set
			{
				if ((this._partner_path != value))
				{
					this._partner_path = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_folder", DbType="VarChar(255)")]
		public string partner_folder
		{
			get
			{
				return this._partner_folder;
			}
			set
			{
				if ((this._partner_folder != value))
				{
					this._partner_folder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_banner_image", DbType="VarChar(255)")]
		public string partner_banner_image
		{
			get
			{
				return this._partner_banner_image;
			}
			set
			{
				if ((this._partner_banner_image != value))
				{
					this._partner_banner_image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_bottom_banner_image", DbType="VarChar(255)")]
		public string partner_bottom_banner_image
		{
			get
			{
				return this._partner_bottom_banner_image;
			}
			set
			{
				if ((this._partner_bottom_banner_image != value))
				{
					this._partner_bottom_banner_image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_top_link", DbType="VarChar(255)")]
		public string partner_top_link
		{
			get
			{
				return this._partner_top_link;
			}
			set
			{
				if ((this._partner_top_link != value))
				{
					this._partner_top_link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner_bottom_link", DbType="VarChar(255)")]
		public string partner_bottom_link
		{
			get
			{
				return this._partner_bottom_link;
			}
			set
			{
				if ((this._partner_bottom_link != value))
				{
					this._partner_bottom_link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kit_banner_image", DbType="VarChar(255)")]
		public string kit_banner_image
		{
			get
			{
				return this._kit_banner_image;
			}
			set
			{
				if ((this._kit_banner_image != value))
				{
					this._kit_banner_image = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
