'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'<summary>
'AffiliatePaymentlistCtrl class.
'</summary>
'<remarks>
'Auto-generated class.
'</remarks>
Partial Public Class AffiliatePaymentlistCtrl

    '<summary>
    'ErrorAlignment control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ErrorAlignment As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'ErrorMessage control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ErrorMessage As Global.System.Web.UI.WebControls.Label

    '<summary>
    'MessageAlignment control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents MessageAlignment As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '<summary>
    'Message control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Message As Global.System.Web.UI.WebControls.Label

    '<summary>
    'ddAffiliates control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents ddAffiliates As Global.System.Web.UI.WebControls.DataList
End Class
