'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'<summary>
'ShippingCarriersControl class.
'</summary>
'<remarks>
'Auto-generated class.
'</remarks>
Partial Public Class ShippingCarriersControl

    '<summary>
    'OriginCity control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents OriginCity As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'OriginState control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents OriginState As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'OriginZip control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents OriginZip As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'BackupShipping control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents BackupShipping As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'CPPanel control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents CPPanel As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'CPActive control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents CPActive As Global.System.Web.UI.WebControls.CheckBox

    '<summary>
    'CPUserName control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents CPUserName As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'UPSPanel control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents UPSPanel As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'UPSLink control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents UPSLink As Global.System.Web.UI.WebControls.LinkButton

    '<summary>
    'UPSActive control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents UPSActive As Global.System.Web.UI.WebControls.CheckBox

    '<summary>
    'UPSRegistered control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents UPSRegistered As Global.System.Web.UI.WebControls.Label

    '<summary>
    'UPSNotRegistered control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents UPSNotRegistered As Global.System.Web.UI.WebControls.Label

    '<summary>
    'FEPanel control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents FEPanel As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'FEActive control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents FEActive As Global.System.Web.UI.WebControls.CheckBox

    '<summary>
    'FedExUserName control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents FedExUserName As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'USPSPanel control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents USPSPanel As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'USPSActive control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents USPSActive As Global.System.Web.UI.WebControls.CheckBox

    '<summary>
    'USPSUserName control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents USPSUserName As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'LTLPanel control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents LTLPanel As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'LTLActive control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents LTLActive As Global.System.Web.UI.WebControls.CheckBox

    '<summary>
    'LTLUserName control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents LTLUserName As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'LTLPassword control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents LTLPassword As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'cmdSave control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents cmdSave As Global.System.Web.UI.WebControls.LinkButton

    '<summary>
    'imgSave control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgSave As Global.System.Web.UI.WebControls.Image
End Class
