'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'<summary>
'TopSubBannerContent class.
'</summary>
'<remarks>
'Auto-generated class.
'</remarks>
Partial Public Class TopSubBannerContent

    '<summary>
    'chkDisplayDynamicContent control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents chkDisplayDynamicContent As Global.System.Web.UI.WebControls.CheckBox

    '<summary>
    'PageName control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents PageName As Global.System.Web.UI.WebControls.RadioButton

    '<summary>
    'rbBannerImage control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents rbBannerImage As Global.System.Web.UI.WebControls.RadioButton

    '<summary>
    'txtBannerImage control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtBannerImage As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'btnBrowse control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents btnBrowse As Global.System.Web.UI.WebControls.ImageButton

    '<summary>
    'NavigationalObjects control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents NavigationalObjects As Global.System.Web.UI.WebControls.RadioButton
End Class
