<?xml version="1.0" encoding="utf-8"?>
<Database Name="QSPFulfillment" EntityNamespace="Data.Entity" ContextNamespace="Data.Context" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=qspdevdb1.qsp;Initial Catalog=QSPFulfillment;Integrated Security=True" SettingsObjectName="BusinessCalendar.Properties.Settings" SettingsPropertyName="QSPFulfillmentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.business_calendar" Member="business_calendars">
    <Type Name="business_calendar">
      <Column Name="business_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="weekend" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="holiday" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>