'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'<summary>
'SimpleSearch class.
'</summary>
'<remarks>
'Auto-generated class.
'</remarks>
Partial Public Class SimpleSearch

    '<summary>
    'Panel1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '<summary>
    'txtSimpleSearch control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents txtSimpleSearch As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'btnSearch control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.LinkButton

    '<summary>
    'imgSearch control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgSearch As Global.System.Web.UI.WebControls.Image
End Class
