'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'<summary>
'StandardSearch class.
'</summary>
'<remarks>
'Auto-generated class.
'</remarks>
Partial Public Class StandardSearch

    '<summary>
    'SimpleKeyword control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents SimpleKeyword As Global.System.Web.UI.WebControls.TextBox

    '<summary>
    'SimpleCategory control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents SimpleCategory As Global.System.Web.UI.WebControls.DropDownList

    '<summary>
    'btnSearch control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.LinkButton

    '<summary>
    'imgSearch control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents imgSearch As Global.System.Web.UI.WebControls.Image

    '<summary>
    'SimpleKeywordGroup1 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents SimpleKeywordGroup1 As Global.System.Web.UI.WebControls.RadioButton

    '<summary>
    'SimpleKeywordGroup2 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents SimpleKeywordGroup2 As Global.System.Web.UI.WebControls.RadioButton

    '<summary>
    'SimpleKeywordGroup3 control.
    '</summary>
    '<remarks>
    'Auto-generated field.
    'To modify move field declaration from designer file to code-behind file.
    '</remarks>
    Protected WithEvents SimpleKeywordGroup3 As Global.System.Web.UI.WebControls.RadioButton
End Class
